[package]
name = "jenner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jenner-macro = { version = "=0.1.0", path = "../jenner-macro" }
futures-core = "0.3"
pin-project = "1"
